### ISSUE TITLE
예제 입력이 비어있는 문제

### ISSUE THREAD

**Issue by Hyeonwoo-Park** [ghkim3221/boj#2]
예제 입력이 비어있는 문제를 생성하면 터집니다

```
v 문제 5337 의 데이터를 다운로드 하였습니다. (0.44 초 사용됨, https://www.acmicpc.net/problem/5337)
Traceback (most recent call last):
  File "C:\Python38\Scripts\boj-script.py", line 11, in <module>
    load_entry_point('boj==0.0.1', 'console_scripts', 'boj')()
  File "C:\Python38\lib\site-packages\boj-0.0.1-py3.8.egg\boj\main.py", line 31, in main
  File "C:\Python38\lib\site-packages\fire-0.3.1-py3.8.egg\fire\core.py", line 138, in Fire
  File "C:\Python38\lib\site-packages\fire-0.3.1-py3.8.egg\fire\core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Python38\lib\site-packages\fire-0.3.1-py3.8.egg\fire\core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Python38\lib\site-packages\boj-0.0.1-py3.8.egg\boj\main.py", line 27, in new
  File "C:\Python38\lib\site-packages\boj-0.0.1-py3.8.egg\boj\problem.py", line 76, in write
  File "C:\Python38\lib\site-packages\boj-0.0.1-py3.8.egg\boj\header.py", line 72, in make_header
  File "C:\Python38\lib\site-packages\boj-0.0.1-py3.8.egg\boj\header.py", line 50, in _make_samples_header
  File "C:\Python38\lib\site-packages\boj-0.0.1-py3.8.egg\boj\header.py", line 26, in _make_sample_header
TypeError: 'NoneType' object is not iterable
```

**Comment by 0x1306e6d** [comment]
Thanks 🙂

**Comment by 0x1306e6d** [comment]
e115ab6 커밋으로 해결
